import Footer from '@components/layout/Footer'
import React from 'react'

const Terms = () => {
    return (
        <div>
            
            <div className='text-white w-[90%] tablet:w-[80%] mx-auto'>
                <div className=" mt-5  tablet:my-8 md:mt-10 md:mb-7">
                    <h1 className='font-bold text-3xl tablet:text-7xl md:text-9xl '>Maven House Terms of Use</h1>
                </div>
                <div className=" py-8 border-b ">
                    <p className='text-sm tablet:text-body1 tablet:text-left '>Welcome to Maven House! These Terms of Use (these “Terms”) govern your use of the Maven House House, Inc. (“Company”, “Maven House”, “us”, “our”, and “we”) websites, maven Househouse.com, maven House.co and world.co (each being the “Website” or the “Site”), the Worlds mobile application and web based platform, and any associated applications or other websites that link to these Terms (collectively, the “Services”). Certain features of the Services may be subject to additional guidelines, terms, or rules, which will be posted on the Site in connection with such features. All such additional terms, guidelines, and rules are incorporated by reference into these Terms.</p>
                    <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>These Terms apply to creators that upload content to the Site (“Creators”), ticket purchasers for Maven House (“Authorized Viewers”), end users who access the Worlds platform and application, and others who visit the Site or use the Services (collectively, “Users”).</p>
                    <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>These Terms create a legal agreement directly between you and Maven House House and explain the rules governing use of the Services. By accessing or using the Services, you acknowledge and agree that you have read, understand, and agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, please do not access or use the Service. You may not access or use the Services or accept the Terms if you are not at least 18 years old.</p>
                    <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>By using this Site, you represent and warrant that you are at least 18 years old and meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use the Site.</p>
                    <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Creators are additionally subject to the Creator Addendum, which is hereby incorporated into these Terms. In the event of a conflict between these Terms and a separate agreement entered into between the Creator and Maven House House (“Individual Creator Agreement”), the Individual Creator Agreement governs.</p>
                    <p className='text-sm capitalize tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Creators are additionally subject to the Creator Addendum, which is hereby incorporated into these Terms. In the event of a conflict between these Terms and a separate agreement entered into between the Creator and Maven House House (“Individual Creator Agreement”), the Individual Creator Agreement governs.</p>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>1. Changes to the Terms of Use</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>We may, from time to time, modify these Terms. Please check this page periodically for updates. We may, from time to time, send e-mails to users with major updates or new features. You are responsible for providing us with your most current e-mail address. If you do not agree to, or cannot comply with, the modified Terms, you must stop using the Services. The updated Terms will take effect upon their posting and will apply on a going-forward basis, unless otherwise provided in a notice to you, and except as provided in Section 11 below. Your continued use of the Services after any such update constitutes your acceptance of such changes.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>2. Accounts</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>In order to use certain features of the Services, you must register for an account (“Account”) and provide certain information about yourself as prompted by the account registration form. You are responsible for ensuring that (a) all required registration information you submit is truthful and accurate and (b) you will maintain the accuracy of such information. We may choose to suspend or terminate your Account at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms.</p>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>You are responsible for maintaining the confidentiality of your Account login information and are fully responsible for all activities that occur under your Account. You agree to immediately notify the Company of any unauthorized use, or suspected unauthorized use, of your Account or any other breach of security. Company cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>3. License and Usage</h2>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>3.1 License to you</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Subject to these Terms, Company grants you a non-transferable, non-exclusive, revocable, limited license to use and access the Services solely for your own personal, noncommercial use. Notwithstanding the foregoing, Creators may use and access the Services for limited commercial use as provided for in the Creator Addendum. Your use of the Services is subject at all times to the Maven House House Privacy Policy and these Terms. Company may revoke this license at any time in its sole discretion with or without notice to you.</p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>3.2 License to Maven House House</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Maven House House allows you to create avatars, stream audio, chat, and to participate in other activities in which you may create, post, transmit, perform or store content, messages, text, sound, images, or other data or materials on the Services (“User Content”).</p>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>You grant to Maven House House and its sub-licensees, to the furthest extent and for the maximum duration permitted by applicable law (including in perpetuity if permitted under applicable law), an unrestricted, worldwide, irrevocable, fully sub-licensable, nonexclusive and royalty free right to: (a) use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display the User Content in any manner or media now known or later developed or discovered; and (b) use the name, identity, likeness, and voice (or other biographical information) that you submit in connection with the User Content.</p>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>You are solely responsible for your User Content and the consequences of posting or publishing it. You represent and warrant that all User Content is (i) created or owned by you, or you otherwise have sufficient right and authority to grant the rights granted herein, and (ii) does not violate the Acceptable Use policy below. Maven House House reserves all rights and remedies against any users who breach these representations and warranties.</p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>3.3 Acceptable Use</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>By using the Services, you agree not to engage in any activity or upload any User Content that, in our sole discretion:</p>
                            <ul className=' list-inside list-disc text-xs tablet:text-body1 tablet:pl-16 text-[#c6c6c6]'>
                                <li className=''>  Is illegal, or violates any federal, state, or local law or regulation; </li>
                                <li>  Violates any third-party right, including, but not limited to, right of privacy, right of publicity, copyright, trademark, patent, trade secret, or any other intellectual property or proprietary rights; </li>
                                <li>  Is harmful, threatening, abusive, harassing, tortious, indecent, defamatory, sexually explicit or pornographic, discriminatory, vulgar, profane, obscene, pornographic, libelous, hate speech, violent or inciting violence, inflammatory, or otherwise objectionable; </li>
                                <li>  Interferes with any other party’s use and enjoyment of the Services; </li>
                                <li>  Attempts to impersonate another person or entity; </li>
                                <li>  Falsely states, misrepresents, or conceals your affiliation with another person or entity; </li>
                                <li>  Accesses or uses the Account of another user without permission; </li>
                                <li>  Distributes computer viruses or other code, files, or programs that interrupt, destroy, or limit the functionality of any computer software or hardware or electronic communications equipment; </li>
                                <li>  Interferes with, disrupts, disables, overburdens, or destroys the functionality or use of any features of the Services, or the servers or networks connected to the Services; </li>
                                <li>  “Hacks” or accesses without permission our proprietary or confidential records, those of another user, or those of anyone else, including by probing, scanning or testing the vulnerability of the Services or any third-party services accessible through the Services; </li>
                                <li>  Improperly solicits personal or sensitive information from other users including without limitation address, credit card or financial account information, or passwords; </li>
                                <li>  Decompiles, reverse engineers, disassembles, or otherwise attempts to derive source code from the Services, except as expressly permitted in these Terms or as required by law; </li>
                                <li>  Removes, circumvents, disables, damages, or otherwise interferes with security-related features, or features that enforce limitations on use of the Services;</li>
                                <li>  Uses automated or manual means to violate the restrictions of the Services, or bypasses or circumvents other measures employed to prevent or limit access, for example by engaging in practices such as “screen scraping,” “database scraping,” or any other activity with the purpose of obtaining lists of users or other information; </li>
                                <li>  Modifies, copies, scrapes or crawls, displays, distributes, publishes, licenses, sells, rents, leases, lends, transfers, or otherwise commercializes any materials or content on the Services, except as specifically authorized by a particular service; </li>
                                <li>  Downloads (other than through page caching necessary for personal use, or as otherwise expressly permitted by these Terms), distributes, posts, transmits, performs, reproduces, broadcasts, duplicates, uploads, licenses, creates derivative works from, or offers for sale any content or other information contained on or obtained from or through the Services, by any means except as provided for in these Terms; or </li>
                                <li>  Attempts to do any of the foregoing. </li>
                            </ul>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>If you are a Creator, your use of the Services must also comport with our Creator Addendum.</p>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Unless otherwise indicated, any future release, update, or other addition to functionality of the Services shall be subject to these Terms. All copyright and other proprietary notices on the Services (or on any content displayed on the Services) must be retained on all copies thereof. </p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>3.4 Enforcement of Acceptable Use Policy</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>We reserve the right (but have no obligation) to review any content posted, uploaded, submitted, or otherwise transmitted to or through the Services (“Content” ), including but not limited to Content made available by Creators (“Creator Content”), and to investigate and/or take appropriate action against you in our sole discretion if you violate the Acceptable Use Policy or any other provision of these Terms or otherwise create liability for us or any other person. Such action may include removing or modifying your Content, terminating your Account, taking appropriate legal action, and/or reporting you to law enforcement authorities.</p>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Without limiting the foregoing, we have the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any materials on or through the Services. <span className='capitalize'>YOU WAIVE AND HOLD HARMLESS THE COMPANY AND ITS AFFILIATES, LICENSEES AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY ANY OF THE FOREGOING PARTIES DURING OR AS A RESULT OF ITS INVESTIGATIONS AND FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER SUCH PARTIES OR LAW ENFORCEMENT AUTHORITIES.</span></p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>3.5 Maintenance</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>You acknowledge and agree that Company will have no obligation to provide you with any support or maintenance in connection with the Services.</p>
                        </div>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>4. Modification and Updates</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Company reserves the right, at any time, to modify, suspend, or discontinue the Services (in whole or in part) with or without notice to you. You agree that Company will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Services or any part thereof. We may update the Services from time to time, but its content is not necessarily complete or up-to-date. Any of the material on the Services may be out of date at any given time, and we are under no obligation to update such material.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>5. Ownership and Intellectual Property</h2>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>5.1 Ownership</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Excluding any Content that you may provide or upload, you acknowledge that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the Services and its content are owned or licensed by Company or Company’s suppliers. All trademarks, logos and service marks (“Marks”) displayed on the Services are our property or the property of other third parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party which may own the Marks.</p>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Neither these Terms, nor your access to the Services, transfers to you or any third party any rights, title or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in these Terms. Company and its suppliers reserve all rights not granted in these Terms. There are no implied licenses granted under these Terms.</p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>5.2 Feedback</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>You may, at your option, provide Maven House House with feedback, comments, and suggestions for improvements to the Services (collectively, “Feedback”). You hereby grant to Maven House House a non-exclusive, worldwide, perpetual, irrevocable, fully paid-up, royalty-free, sublicensable and transferable license to any Feedback under any and all intellectual property rights that you own or control.</p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>5.3 Our Proprietary Rights</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>The Services contain materials that are proprietary and are protected by copyright laws, international treaty provisions, trademarks, service marks, and other intellectual property laws and treaties. The Services are also protected as a collective work or compilation under copyright and other laws and treaties. You agree to abide by all applicable copyright and other laws, as well as any additional copyright notices or restrictions contained on the Services. You acknowledge that the Services contain original works that have been developed, compiled, prepared, revised, selected, and arranged by Maven House House and others, including Creators, through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and which constitute valuable intellectual property of Maven House House and such others. All present and future rights in and to trade secrets, patents, designs, copyrights, trademarks, database rights, service marks, know-how, and other intellectual property or other proprietary rights of any type, documentation, any improvements, design contributions, or derivative works thereto, and any knowledge or process related thereto, including rights in and to all applications and registrations relating to the Services, shall, as between you and Maven House House, at all times be and remain the sole and exclusive property of Maven House House.</p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>5.4 DMCA Policy</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Company respects the intellectual property of others and requires that users of the Services, including but not limited to Site visitors, Creators, and viewers of Creator Content, do the same. In connection with our Services, we have adopted and implemented a policy respecting copyright law that provides for the removal of any infringing materials and for the termination, in appropriate circumstances, of users who are repeat infringers of intellectual property rights, including copyrights. If you believe that one of our users is, through the use of our Services, unlawfully infringing the copyright(s) in a work, and wish to have the allegedly infringing material removed, the following information in the form of a written notification (pursuant to the Digital Millennium Copyright Act ( “DMCA”), 17 U.S.C. § 512(c)) must be provided to our designated Copyright Agent at:</p>
                        </div>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>6. Terms of Sale</h2>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>6.1 Ticket Purchases</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>In purchasing a ticket to a Maven House, you agree to be governed by these Terms. Tickets provide access to additional Services, such as viewing Maven House. Company does not guarantee the performance of any Maven House or other event for which tickets are purchased. Performance times are approximations and are not guaranteed. Additional service fees may be included with ticket purchases.</p>
                        </div>
                        <div className="">
                            <h4 className='tablet:pl-9 pl-4 text-sm tablet:text-body2  font-semibold tablet:mb-2'>6.2 Ticket Refunds</h4>
                            <p className='text-xs tablet:pl-14 tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Ticket purchases are refundable only as set forth in the Refund Policy. Notwithstanding the Refund Policy, at our sole discretion we may provide a refund, discount, or other consideration (“Credits”) for some or all users. The amount and form of such Credits, and the decision to provide them, are at our sole and absolute discretion. The provision of Credits in one instance does not entitle you to Credits in the future for similar instances, nor does it obligate us to provide Credits in the future.</p>
                        </div>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>7. Third-Party Links & Ads; Other Users</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>The Services may contain links to third-party websites and services, and/or display advertisements for third parties (collectively, “Third-Party Links & Ads”). Such Third-Party Links & Ads are not under the control of Company, and Company is not responsible for any Third-Party Links & Ads. Company provides access to these Third-Party Links & Ads only as a convenience to you, and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Links & Ads. You use all Third-Party Links & Ads at your own risk, and should apply a suitable level of caution and discretion in doing so. When you click on any of the Third-Party Links & Ads, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices. You further acknowledge and agree that Maven House House shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any linked sites or resources.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>8. Geographic Restrictions</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>Maven House House is based in the United States. We make no claims that the Services or any of its content is accessible or appropriate outside of the United States. Access to the Services may not be legal by certain persons or in certain countries. If you access the Services from outside the United States, you do so on your own initiative and are responsible for compliance with local laws.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>9. Warranties, Disclaimers and Limitation of Liability</h2>
                        <p className='text-sm capitalize'>
                            THE SERVICES AND THE CONTENT CONTAINED THEREIN, WHETHER PROVIDED BY Maven House HOUSE, ITS LICENSORS, ITS VENDORS OR ITS USERS, AND OTHER INFORMATION ON OR ACCESSIBLE FROM THE SERVICES ARE PROVIDED “AS IS” WITHOUT WARRANTY, REPRESENTATION, CONDITION, OR GUARANTEE OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES, REPRESENTATIONS, CONDITIONS OR GUARANTEES OF QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, ALL OF WHICH ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. SPECIFICALLY, BUT WITHOUT LIMITATION, Maven House HOUSE DOES NOT WARRANT THAT: (i) THE INFORMATION AVAILABLE ON THE SERVICES IS FREE OF ERRORS; (ii) THE FUNCTIONS OR FEATURES WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS; (iii) DEFECTS WILL BE CORRECTED, OR (iv) THE SERVICES OR THE SERVER(S) THAT MAKE THE SERVICES AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. IN NO EVENT SHALL Maven House HOUSE OR ITS AFFILIATES, LICENSORS, VENDORS, OR ANY OF THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, OR OTHER REPRESENTATIVES BE LIABLE TO YOU OR ANY OTHER PERSON OR ENTITY FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, LOSS OF USE, OR COSTS OF OBTAINING SUBSTITUTE GOODS OR SERVICES), ARISING OUT OF OR IN CONNECTION WITH THE SERVICES, ANY MATERIALS, INFORMATION, OR RECOMMENDATIONS APPEARING ON THE SERVICES, OR ANY LINK PROVIDED ON THE SERVICES, WHETHER OR NOT Maven House HOUSE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND WHETHER BASED UPON WARRANTY, CONTRACT, TORT, STRICT LIABILITY, VIOLATION OF STATUTE, OR OTHERWISE. THIS EXCLUSION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. IN ANY EVENT, OUR AGGREGATE LIABILITY WILL NOT EXCEED THE AMOUNT PAID FOR THE SERVICES TO WHICH THE CLAIM RELATES OR, IF THE CLAIM DOES NOT RELATE TO A PAID PRODUCT OR SERVICE, $100. Maven House HOUSE DOES NOT WARRANT, ENDORSE, GUARANTEE OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES OR ANY THIRD-PARTY SERVICE MADE AVAILABLE THROUGH THE SERVICES, AND Maven House HOUSE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD PARTIES. Maven House HOUSE WILL NOT BE LIABLE FOR THE OFFENSIVE OR ILLEGAL CONDUCT OF ANY THIRD PARTY. YOU VOLUNTARILY ASSUME THE RISK OF HARM OR DAMAGE FROM THE FOREGOING. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE AND TO THE FULLEST EXTENT PERMITTED BY LAW.
                        </p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>10. Indemnification</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>You agree to defend, indemnify and hold Company (and its officers, employees, and agents) harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Services, (b) your violation of these Terms, (c) your violation of applicable laws or regulations or (d) your Content. Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of Company. Company will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>11. Mandatory Arbitration and Class Action Waiver</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'> <span className='text-semibold'>
                            Application. </span> You and Company agree that these Terms affect interstate commerce and that the Federal Arbitration Act governs the interpretation and enforcement of these arbitration provisions. This Section is intended to be interpreted broadly and governs any and all disputes between us including but not limited to claims arising out of or relating to any aspect of the relationship between us, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory; claims that arose before these Terms or any prior agreement (including, but not limited to, claims related to advertising); and claims that may arise after the termination of these Terms. The only disputes excluded from this broad prohibition are the litigation of certain intellectual property and small court claims, as provided below.</p>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'> <span className='text-semibold'>
                            Initial Dispute Resolution. </span>Most disputes can be resolved without resort to arbitration. If you have any dispute with us, you agree that before taking any formal action, you will contact us and provide a brief, written description of the dispute and your contact information (including your username, if your dispute relates to an Account). Except for intellectual property and small claims court claims, the parties agree to use their best efforts to settle any dispute, claim, question, or disagreement directly through consultation with Company, and good faith negotiations shall be a condition to either party initiating a lawsuit or arbitration.</p>
                            <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'> <span className='text-semibold'>
                            Binding Arbitration. </span>If the parties do not reach an agreed-upon solution within a period of thirty (30) days from the time informal dispute resolution is initiated under the Initial Dispute Resolution provision above, then either party may initiate binding arbitration as the sole means to resolve claims, subject to the terms set forth below. Specifically, all claims arising out of or relating to these Terms (including the Terms’ formation, performance, and breach), the parties’ relationship with each other, and/or your use of Company shall be finally settled by binding arbitration administered by the JAMS Comprehensive Arbitration Rules & Procedures (“JAMS”). The JAMS rules will govern payment of all arbitration fees. Except as provided below, you will not be responsible for any arbitration filing fees that exceed the amount you would pay for a court filing, or $200, whichever is greater. For non-frivolous and non-time barred claims. At the conclusion of the Arbitration, Company will reimburse all arbitration fees for claims less than $75,000. Company will not seek its attorneys’ fees and costs in arbitration unless the arbitrator determines that your claim is frivolous or time-barred.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>12. Controlling Law and Severability</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>These Terms shall be construed in accordance with and governed by the laws of California notwithstanding its conflicts of law principles. Any dispute arising out of these terms and conditions or the use of this site shall be initiated and conducted in the state or federal courts of Santa Clara County, California, and you and Maven House House consent to the exclusive jurisdiction of such courts.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>13. Prohibited Entities</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>You agree you are not i) in a location embargoed under U.S. Economic Sanctions, such as Iran, North Korea, Cuba, Crimea, or Syria, ii) are listed on any restricted parties list issued by any U.S. or European governmental entity or international organization ( “Restricted Parties Lists”), or iii) will utilize this product to service, directly or indirectly, a sanctioned location or any entity appearing on any Restricted Parties Lists.</p>
                    </div>
                    <div className="">
                        <h2 className='tablet:mb-3 text-xl font-semibold tablet:text-4xl '>14. General Terms</h2>
                        <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>These Terms (and all terms and conditions incorporated herein) constitute the entire agreement between you and Maven House House and govern your use of the Services, and supersede any other agreements between you and Maven House House on the subject matter, except for Individual Creator Agreements (which shall take precedence in the event of a conflict with these Terms). These Terms, and any rights or licenses granted hereunder, may not be assigned or delegated by you. These Terms, and any rights or licenses granted hereunder, may be assigned or delegated by Maven House House without restriction. These Terms bind and inure to the benefit of each party and the party’s successors and permitted assigns. These Terms may not be modified by an oral statement by a representative of Maven House House. No agency, partnership, joint venture or employee-employer relationship is intended or created by these Terms. You agree that any agreements made by and between you and us in electronic form are as legally binding as if made in physical written form. If you are using the Services for or on behalf of the U.S. government, your license rights do not exceed those granted to non-government consumers. The section titles in these Terms are for convenience only and have no legal or contractual effect. Any provision of these Terms that by its nature is reasonably intended to survive beyond termination of these Terms shall survive.</p>
                    </div>
                 </div>
                <div className=" mt-5  tablet:my-8 md:mt-10 md:mb-7">
                    <h1 className='font-bold text-3xl tablet:text-7xl md:text-9xl '>Exhibit A - Creator Addendum</h1>
                </div>
                <div className="">
                    <p className='text-sm tablet:text-body1 tablet:text-left tablet:mb-4 mb-2'>If you provide and/or upload content to the Services for the purpose of holding a Maven House or an otherwise gated event, this Creator Addendum applies to your use of the Maven House House Creator services. This Creator Addendum should be read in conjunction with our Terms of Use and Privacy Policy, all of which create a binding agreement between you ( “Creator” or “You”) and Maven House House Inc. ( “Maven House House”). In the event of any consistencies between the Addendum and any other terms, this Addendum shall control. Maven House House may update these terms at any time by posting on this page.</p>
                    <div className="">
                        <ul className='list-decimal list-inside pl-2 text-xs tablet:text-body1 text-[#c6c6c6] tablet:pl-16'>
                                <li>Maven House. As among the parties and except as set forth herein, Creator shall be responsible for effecting the Maven House(s) in accordance with the terms of this Agreement and Maven House House’s Terms of Use, including production and delivery of the live feed or recording (as applicable) of the Maven House(s) in accordance with Maven House House’s technical specifications. Maven House House provides a platform for the ticketing and ingestion and distribution of the Maven House(s). Maven House House reserves the right not to air any Maven House at its sole discretion.</li>
                                <li>Compensation. In consideration of all rights, benefits, and opportunities provided to Maven House House under this Agreement, Maven House House will pay to Creator its earnings in accordance with each Maven House less the following deductions: (i) Maven House House’s service fee, (ii) any third party transaction fees, (iii) taxes collected at purchase, (iv) if applicable, a PRO deduction, and (v) any other deductions that Maven House House notifies you of in advance. Maven House House may collect sales, VAT and GST taxes at point of purchase from Authorized Viewers in accordance with the tax rates identified by its third party vendor(s) and when required, remit such tax amounts to local authorities. As between the parties, Creator shall solely be responsible for the payment of any other taxes required in connection with any amounts due or payable or required to be withheld and remitted under this Agreement and shall timely file all required tax returns in connection with such withholdings and payments. Creator payments may be subject to additional terms associated with third party platforms (e.g. Paypal, Stripe). Maven House House reserves the right to withhold or delay Creator payments, at its discretion, for such purposes such as suspicion of fraud, mistake, error in denomination, violation of applicable law or any applicable Maven House House or third party terms. Depending on its availability, Maven House House may offer Creators payout through cryptocurrency via Stripe. If Creator opts to use Stripe’s Cryptocurrency Payment services, you understand and acknowledge the risks associated with transacting in cryptocurrency and release Maven House House of any liability associated with such transactions (including, but not limited to, fluctuations in value, security breaches, and transaction errors).</li>
                                <li>Creator Obligations. Creator is solely responsible for creation of any content to be distributed on the Maven House House platform. Creator shall be responsible, at Creator sole cost and expense, for securing any and all necessary third party rights, licenses, clearances, and permissions (including, but not limited to, all necessary publishing and record label clearances, synchronization and mechanical rights) required in connection with Creator’s capture and/or exploitation of the Maven House and Maven House House’s distribution of the Maven House in accordance with this agreement (other than obtaining blanket performance licenses, if coverage is agreed in writing with Maven House House prior to the Maven House). Creator shall be responsible for complying with Maven House House’s content and advertising restrictions, including all prohibitions on the inclusion of drug use, smoking, hate speech and nudity during any Maven House. Creator represents and warrants that the exhibition of the Licensed Content will not violate any applicable law or regulation in any of the territories where tickets are sold.</li>
                                <li>Maven House House’s Rights and Obligations. Maven House House provides you the right to use its platform to allow Authorized Viewers to access each Maven House, via live streaming (or video-on-demand). Maven House House shall have the sole right to monetize the stream of the Maven House(s), including selling advertisements and sponsorships for the stream of the Maven House(s). In the event that Creator wishes to sell any advertisements, sponsorships and product placements or include any third party branding in the stream of the Maven House, Creator must obtain the prior written consent of Maven House House, which consent may be conditioned on the receipt of indemnification from the advertiser/sponsor in favor of Maven House House.</li>
                                <li>Marks. Creator grants Maven House House the royalty-free right to use Creator’s voice, sounds, professional name, appearance, biographical information, trademarks and service marks and all other rights of publicity and aspects of their identity (collectively, “Likeness”) in connection with the Maven House and the marketing and promotion of the Maven House. Creator owns all right, title and interest in and to the Likeness. Maven House House grants to Creator the right to use Maven House House’s logo, brand name and URL (the “Maven House House Marks”), in connection with promotions for the Maven House or for referential purposes when sharing the Creator Content after the Term, provided that the Maven House House Marks is used in accordance with any instructions provided in writing to Creator and Maven House House shall have the right to request removal of its Maven House House Marks at its discretion.</li>
                                <li>Non-Disparagement. Creator shall refrain from making public statements that may be inconsistent with the positive image and/or goodwill with which Maven House House wishes to associate and from taking any action that reflects negatively upon Maven House House. If Creator (i) commits or is accused of committing any civil or criminal offense under federal state or local law, or (ii) is involved, or accused of being involved in any situation or occurrence which subjects Creator to disrepute, widespread contempt, or which is widely deemed by members of the public, to embarrass, offend, insult, denigrate individuals of groups, then Maven House House shall have the right in its sole discretion to terminate this Agreement upon notice with no further obligation to Creator. If Maven House House terminates under this section, Creator forfeits any outstanding compensation to Maven House House.</li>
                                <li>Representations and Warranties. Creator represents and warrants that it (i) has all rights necessary to grant to Maven House House the rights set forth in this Agreement, (ii) that the exploitation of such rights by Maven House House (including the Licensed Content and Likeness) shall not violate any right of any third party, including, without limitation, any privacy, publicity, contractual or intellectual property right, (iii) that Maven House House will not need to obtain licenses from any third party or pay royalties to any third party with respect to the streaming or other permitted distribution of the content; (iv) that you have obtained appropriate releases (if necessary) from all persons who appear in the content; and (v) that it will comply with any and all federal, state, and local laws, rules and regulations applicable to the production and content of the Maven House(s), including, without limitation, obtaining all permits, licenses, and authorizations required to produce the Maven House(s).</li>
                                <li>Indemnification. You will indemnify, defend and hold harmless Maven House House, including Maven House House’s equity holders, officers, directors, managers, employees, agents and representatives, from and against all damages, liabilities and costs (including reasonable outside attorneys’ fees and expenses) based upon or arising out of any claim arising from or relating to (a) the content you submit to or through the Maven House House services; and (b) allegations of actions or omissions by you that (regardless if proven) would constitute a breach of this Agreement.</li>
                                <li>Relationship Among the Parties. The relationship among the parties hereto is solely that of independent contractors. For purposes of this Creator Addendum, no party is or shall be construed to be a partner, joint venturer, employee, agent, representative or participant of or with either of the other parties for any purpose whatsoever. No party has any right or authority whatsoever to assume or create any liability, obligation or responsibility, or make any representation or warranty, express or implied, on behalf of or in the name of any other party.</li>
                                <li>Data Sharing. Maven House House may provide certain data to Creator, including information relating to ticket purchases, ticketholders, and other information associated with fulfilment of merchandise orders. The collection and use of such data shall be in accordance with Maven House House’s Privacy Policy, and the .Data Protection Addendum. The Privacy Policy and Data Protection Addendum are hereby incorporated into this Creator Addendum.</li>
                                <li>Content. All materials (including the Maven House, marketing and promotional materials, and merchandise) provided by Creator (or a third party on Creator’s behalf) or uploaded to Maven House House shall be considered “Creator Content.” Subject to the terms of this Agreement, Creator hereby grants to Maven House House a perpetual, irrevocable, non-exclusive, sublicensable, worldwide, royalty-free right and license to use, distribute, record, stream, reproduce, publicly perform, publicly display, transmit, modify, make derivative works, and edit the Creator Content and any and all works included therein, in any manner or media, (i) in connection with streaming of Maven House, (ii) on the Maven House House website and social media channels, (iii) in connection with providing the services, and (iv) in connection with promotional campaigns and/or other audiovisual works for the Maven House or Maven House House. Creator owns all right, title and interest in and to the Creator Content.</li>
                        </ul>
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    )
}

export default Terms